version: '3.8'

services:
  nginx:
    build:
      context: .
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    logging:
      driver: splunk
      options:
        splunk-token: "Your_HEC_Tolen"
        splunk-url: "https://localhost:8088"
        splunk-insecureskipverify: "true"
        splunk-source: "nginx"
        splunk-sourcetype: "nginx_logs"
        splunk-index: "main"
    networks:
      - appnet

  php-fpm:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./site:/var/www/html
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
